import { writable } from 'svelte/store';
export const topZ = writable(1);
export const windowList = writable([]);
export const minimizedSig = writable([]);
export const activeSignal = writable(null);
export const focusWindowTop = writable(null);
export const url = writable(null);
export const activeTab = writable(null);
export const tabID = writable(null);
export const tabName = writable("Example Tab");
export const tabIcon = writable('https://galxy.it.com/assets/img/icons/browser.png');
