name: Mirror to GitLab

on:
  push:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitLab
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/Hydra.Network/galaxy/galaxyv7.git

          git push --force --all gitlab
          git push --force --tags gitlab
